# Generated by Django 3.0.8 on 2020-08-02 11:26

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Contact Address')),
                ('contact_first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('contact_last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('contact_email', models.CharField(max_length=255, verbose_name='Email Address')),
                ('contact_description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
