# Generated by Django 3.0.8 on 2020-08-24 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('businessname', models.CharField(blank=True, max_length=255, null=True)),
                ('taxnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_details', models.CharField(blank=True, max_length=500, null=True)),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('agency_contact_person', models.FileField(blank=True, null=True, upload_to='')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('agency_cover_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
