# Generated by Django 3.0.8 on 2020-08-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200824_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agent',
            new_name='agency_agent',
        ),
    ]
