# Generated by Django 3.0.8 on 2020-08-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
